sonar.projectKey=sw5005-sus_ceramicraft-mcp-server
sonar.organization=sw5005-sus
sonar.projectName=ceramicraft-mcp-server

sonar.sources=src/ceramicraft_mcp_server
sonar.tests=tests
sonar.exclusions=src/ceramicraft_mcp_server/pb/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
